services:
  app:
    image: quarkus/hyperspeed-quarkus-jvm:latest
    container_name: hyperspeed-quarkus
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 12g
