services:
  app:
    image: quarkus/jvm
    container_name: hyperspeed-quarkus-jvm
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 12g
